#!/usr/bin/env bash

# create-sign-ca-keys - create self-signed keys for certificate authority purposes
# Copyright (C) 2024  Ira Peach
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# there may be two openssl binaries...
openssl="/usr/bin/openssl"

dir="$1"
subject_suffix="$2"

if [[ -z $dir ]] || [[ -z $subject_suffix ]]; then
    echo "usage: $(basename "$0") CA_DIR SUBJECT_SUFFIX" >&2
    echo "" >&2
    echo "example: $(basename "$0") /usr/local/etc/ssl/ca.example.lan 'O=My Org/C=MyCountry'" >&2
    exit 1
fi

dir="$(realpath "$dir")"

domain="$(basename "$dir")"
openssl_config="$domain.cnf"
private_key="$domain.key"
public_key="$domain.crt"

subject="/CN=$domain/$subject_suffix"

# Don't use any openssl config to muck up openssl invocations
export OPENSSL_CONF=""

mkdir -p "$dir" &&
pushd "$dir" >/dev/null &&

cat <<EOF>"$openssl_config" &&
[ v3_ca ]
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid:always,issuer
basicConstraints = critical,CA:TRUE
keyUsage = cRLSign, keyCertSign
EOF

if [ ! -f "$private_key" ]; then
  echo "note: Private key does not exist; creating new private key '$private_key'" &&
  "$openssl" ecparam -name secp521r1 -genkey -noout -out "$private_key"
  echo ""
fi &&

echo "note: Creating new self-signed certificate using private key '$private_key', subject '$subject', output public key '$public_key'" &&
"$openssl" x509 -extensions v3_ca -key "$private_key" -new -subj "$subject" -out "$public_key" -days 365 -extfile "$openssl_config" &&

cat <<EOF>"create-sign-ca-keys.sh" &&
#!/bin/sh

create-sign-ca-keys '$dir' '$subject_suffix'
EOF
chmod 755 "create-sign-ca-keys.sh"
